version: '3.8'
services:
  backend:
    build:
      context: ./Backend/TaxCalculator.WebApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaxCalculatorDb;User Id=sa;Password=YourStrong@Passw0rd;MultipleActiveResultSets=true
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./Frontend/TaxCalculator.UI
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"