version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/TaxCalculator.UI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - tax-calculator-net

  backend:
    build:
      context: ./backend
      dockerfile: TaxCalculator.WebApi/Dockerfile
    ports:
      - "5000:8080"  # Host:5000 maps to Container:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080  # Matches EXPOSE 8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/taxcalculator.db
    volumes:
      - sqlite-data:/app
    networks:
      - tax-calculator-net

networks:
  tax-calculator-net:
    driver: bridge

volumes:
  sqlite-data: